# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://lexmartin.mx
title: Alejandro Martín
email: lexmartin.mx@gmail.com
author: LexMartín
description: > # "Write an awesome description for your new site here. 
  Ingeniero en Telemática, Programdor, Maker
copyright: '&copy; 2019 LexMartín.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
 # - title: twitter
 #   url: https://twitter.com/lexmartin_mx
  - title: github
    url: https://github.com/lexmartin
  - title: linkedin
    url: https://linkedin.com/in/lexmartin-mx
